Task 12.7
AdamPawlinski/task-12.7 pull request #1
Opened 2018-04-06 20:16 UTC by AdamPawlinski

Task 12.7 finished. Please accept merging.

2018-04-08 08:52 UTC, matwjablonski requested changes

2018-04-08 08:52 UTC, matwjablonski commented on index.html
>  <head>
lang for html

2018-04-08 08:52 UTC, matwjablonski commented on js/App.js
> +  'X-Client-Id': '3026',
id can be a number ;)

2018-04-08 08:52 UTC, matwjablonski commented on js/Card.js
>  		cardDeleteBtn.click(function(){
better use method `on` instead of `click`

2018-04-15 04:05 UTC, AdamPawlinski commented
finished. ask for acceptance.

2018-04-15 08:50 UTC, matwjablonski approved these changes

2018-09-12 04:28 UTC, merged